# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.key }}
        name: id_rsa # optional
        config: |
          Host *
             IdentityFile ~/.ssh/id_rsa
             StrictHostKeyChecking no
             UserKnownHostsFile /dev/null
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: chart

    - name: Checkout tools repo
      uses: actions/checkout@v2
      with:
        repository: git@github.com/AuroTFP/AuroTFP.github.io.git
        path: pages
        ssh-key: ${secrets.key}
    
    # Runs a set of commands using the runners shell
    - name: packge
      run: |
        curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
        helm package chart
        helm repo index . --url https://AuroTFP.github.io/helm/
        mkdir -p pages/helm
        cp chart/*.tgz pages/helm/
        cp index.yaml pages/helm/
        cd pages
        git add helm
        git commit -m .
        git push
        
        
        
